// Copyright (C) 2026 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

use axum::{Router, routing::get};
use polkadot_rest_api_config::ChainType;

use crate::{
    handlers::pallets,
    routes::{API_VERSION, RegisterRoute, RouteRegistry},
    state::AppState,
};

pub fn routes(registry: &RouteRegistry, chain_type: &ChainType) -> Router<AppState> {
    let router = Router::new()
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/dispatchables",
            "get",
            get(pallets::get_pallets_dispatchables),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/dispatchables/:dispatchableId",
            "get",
            get(pallets::get_pallet_dispatchable_item),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/consts",
            "get",
            get(pallets::pallets_constants),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/consts/:constantItemId",
            "get",
            get(pallets::pallets_constant_item),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/errors",
            "get",
            get(pallets::get_pallet_errors),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/errors/:errorItemId",
            "get",
            get(pallets::get_pallet_error_item),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/events",
            "get",
            get(pallets::get_pallet_events),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/events/:eventItemId",
            "get",
            get(pallets::get_pallet_event_item),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/storage",
            "get",
            get(pallets::get_pallets_storage),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/:palletId/storage/:storageItemId",
            "get",
            get(pallets::get_pallets_storage_item),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/assets/:assetId/asset-info",
            "get",
            get(pallets::pallets_assets_asset_info),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/pool-assets/:assetId/asset-info",
            "get",
            get(pallets::pallets_pool_assets_asset_info),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/foreign-assets",
            "get",
            get(pallets::pallets_foreign_assets),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/staking/progress",
            "get",
            get(pallets::pallets_staking_progress),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/staking/validators",
            "get",
            get(pallets::pallets_staking_validators),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/nomination-pools/info",
            "get",
            get(pallets::pallets_nomination_pools_info),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/nomination-pools/:poolId",
            "get",
            get(pallets::pallets_nomination_pools_pool),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/asset-conversion/liquidity-pools",
            "get",
            get(pallets::get_liquidity_pools),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/asset-conversion/next-available-id",
            "get",
            get(pallets::get_next_available_id),
        )
        .route_registered(
            registry,
            API_VERSION,
            "/pallets/on-going-referenda",
            "get",
            get(pallets::pallets_on_going_referenda),
        );

    // Only register /rc/ routes for parachains, not relay chains
    if *chain_type != ChainType::Relay {
        router
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/staking/progress",
                "get",
                get(pallets::rc_pallets_staking_progress),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/staking/validators",
                "get",
                get(pallets::rc_pallets_staking_validators),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/consts",
                "get",
                get(pallets::rc_pallets_constants),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/consts/:constantItemId",
                "get",
                get(pallets::rc_pallets_constant_item),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/errors",
                "get",
                get(pallets::rc_pallet_errors),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/errors/:errorItemId",
                "get",
                get(pallets::rc_pallet_error_item),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/events",
                "get",
                get(pallets::rc_pallet_events),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/events/:eventItemId",
                "get",
                get(pallets::rc_pallet_event_item),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/dispatchables",
                "get",
                get(pallets::rc_pallets_dispatchables),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/dispatchables/:dispatchableId",
                "get",
                get(pallets::rc_pallet_dispatchable_item),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/storage",
                "get",
                get(pallets::rc_get_pallets_storage),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/:palletId/storage/:storageItemId",
                "get",
                get(pallets::rc_get_pallets_storage_item),
            )
            .route_registered(
                registry,
                API_VERSION,
                "/rc/pallets/on-going-referenda",
                "get",
                get(pallets::rc_pallets_on_going_referenda),
            )
    } else {
        router
    }
}
