apiVersion: 1

datasources:
  - name: Benchmarks SQLite
    type: frser-sqlite-datasource
    uid: benchmarks
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /var/lib/grafana/data/benchmarks.db
